name: zimple
description: Calendar planning application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.2
  modal_progress_hud: ^0.1.3
  calendar_views: ^0.5.2
  intl: ^0.17.0
  scroll_snap_list: ^0.7.0
  firebase_database: ^6.1.0
  tuple: ^1.0.3
  persistent_bottom_nav_bar: any
  flutter_datetime_picker: ^1.5.0
  google_fonts: ^2.0.0
  loader_overlay: ^2.0.0
  rxdart: ^0.26.0
  firebase_storage: ^8.0.1
  infinite_listview: ^1.1.0
  image_picker: ^0.7.4
  uuid: ^3.0.3
  firebase_messaging: ^9.1.1
  provider: ^4.3.3
  maps_launcher: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
  fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
      - asset: fonts/Montserrat/Montserrat-Light.ttf
  - family: Biryani
    fonts: 
      - asset: fonts/Biryani/Biryani-Regular.ttf
      - asset: fonts/Biryani/Biryani-Light.ttf
      - asset: fonts/Biryani/Biryani-Bold.ttf
      - asset: fonts/Biryani/Biryani-ExtraBold.ttf
      - asset: fonts/Biryani/Biryani-SemiBold.ttf
      - asset: fonts/Biryani/Biryani-ExtraLight.ttf
  - family: Biryani
    fonts: 
      - asset: fonts/Poppins/Poppins-Black.ttf
      - asset: fonts/Poppins/Poppins-BlackItalic.ttf
      - asset: fonts/Poppins/Poppins-Bold.ttf
      - asset: fonts/Poppins/Poppins-Regular.ttf
      - asset: fonts/Poppins/Poppins-SemiBold.ttf
      - asset: fonts/Poppins/Poppins-Light.ttf
      - asset: fonts/Poppins/Poppins-Medium.ttf
      - asset: fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: fonts/Poppins/Poppins-ExtraLight.ttf