name: zimple
description: Zimple projektverktyg
version: 1.3.0+64

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clipboard: ^0.1.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  encrypt: ^5.0.1
  excel: ^2.1.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_database: ^10.2.7
  firebase_dynamic_links: ^5.3.7
  firebase_messaging: ^14.6.9
  firebase_remote_config: ^4.2.7
  firebase_storage: ^11.2.8
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  fluttericon: ^2.0.0
  flutter_pdfview: ^1.3.1
  font_awesome_flutter: ^10.4.0
  focus_detector: ^2.0.0
  image_picker: ^0.8.4+4
  infinite_listview: ^1.1.0
  intl: ^0.18.0
  loader_overlay: ^2.0.0
  logger: ^1.0.0
  maps_launcher: ^2.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  pdf: ^3.4.2
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.2
  quiver: ^3.0.1
  rive: ^0.9.1
  rxdart: ^0.27.3
  scroll_snap_list: ^0.9.1
  share_plus: ^4.5.3
  shared_preferences: ^2.0.6
  snapping_sheet: ^3.1.0
  styled_widget: ^0.4.0+3
  tuple: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.6
  uuid: ^3.0.3
  flutter_email_sender: ^5.2.0
  smooth_page_indicator: ^1.0.0+2
  geocoding: ^2.1.0
  geolocator: ^8.2.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.0.1+1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appicon.jpg"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/rives/
  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans/FiraSans-Regular.ttf
        - asset: fonts/FiraSans/FiraSans-Bold.ttf
        - asset: fonts/FiraSans/FiraSans-ExtraBold.ttf
        - asset: fonts/FiraSans/FiraSans-Medium.ttf
        - asset: fonts/FiraSans/FiraSans-Thin.ttf
        - asset: fonts/FiraSans/FiraSans-Light.ttf
        - asset: fonts/FiraSans/FiraSans-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
    - family: Biryani
      fonts:
        - asset: fonts/Biryani/Biryani-Regular.ttf
        - asset: fonts/Biryani/Biryani-Light.ttf
        - asset: fonts/Biryani/Biryani-Bold.ttf
        - asset: fonts/Biryani/Biryani-ExtraBold.ttf
        - asset: fonts/Biryani/Biryani-SemiBold.ttf
        - asset: fonts/Biryani/Biryani-ExtraLight.ttf
    - family: Biryani
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
